name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  NODE_VERSION: '20'

jobs:
  test:
    name: Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Build package
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Verify package integrity
      run: npm run health-check

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.node-version == 20
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        # token: ${{ secrets.CODECOV_TOKEN }}  # Uncomment if you add the token

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == 20
      with:
        name: dist-files
        path: dist/
        retention-days: 7

  docker-test:
    name: Docker Test
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t aoe2-rms-parser .

    - name: Test Docker image
      run: |
        # Test that the Docker image can run basic commands
        docker run --rm aoe2-rms-parser node -e "console.log('Docker image works!')"
        
        # Test that the parser can be imported
        docker run --rm aoe2-rms-parser node -e "const { parse } = require('./dist/index.js'); console.log('Parser imported successfully!')"
        
        # Test basic parsing functionality
        docker run --rm aoe2-rms-parser node -e "const { parse } = require('./dist/index.js'); const result = parse('<PLAYER_SETUP>\nrandom_placement'); console.log('Parsing works:', result.ast ? 'SUCCESS' : 'FAILED');"
        
        # Test linting functionality
        docker run --rm aoe2-rms-parser node -e "const { parse, lint } = require('./dist/index.js'); const { ast } = parse('<PLAYER_SETUP>\nrandom_placement'); const errors = lint(ast); console.log('Linting works:', Array.isArray(errors) ? 'SUCCESS' : 'FAILED');"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test, docker-test]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Build package
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
